# Generated by Django 3.0.5 on 2020-04-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siberian_designs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examples',
            new_name='Example',
        ),
    ]
