# Generated by Django 3.0.5 on 2020-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siberian_designs', '0003_auto_20200422_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(default='default', max_length=1000, verbose_name='Описание'),
        ),
    ]
