# Generated by Django 3.0.5 on 2020-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siberian_designs', '0004_example_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='title',
            field=models.TextField(default='default', max_length=200),
        ),
    ]
